
# When running forge, you can specify the profile to use using the FOUNDRY_PROFILE environment variable.
[profile.default]
solc = '0.8.24'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
via_ir = true
cache_path = 'cache_forge'
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20_000

[profile.ci]
verbosity = 4

[rpc_endpoints]
amoy = "${AMOY_ENDPOINT}${ALCHEMY_API_KEY}"
