
# When running forge, you can specify the profile to use using the FOUNDRY_PROFILE environment variable.
[profile.default]
solc = '0.8.24'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
ffi = true
ast = true
via_ir = true
cache_path = 'cache_forge'
gas_reports = ["*"]
build_info = true
optimizer = true
optimizer_runs = 20_000
extra_output = ["storageLayout"]

[profile.ci]
verbosity = 4

[rpc_endpoints]
amoy = "${AMOY_ENDPOINT}${ALCHEMY_API_KEY}"
