
# When running forge, you can specify the profile to use using the FOUNDRY_PROFILE environment variable.
[profile.default]
# solc = '0.8.26'
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
via_ir = true
cache_path = 'cache'
gas_reports = ["*"]
offline = true
ffi = true
ast = true
build_info = true
optimizer = true
optimizer_runs = 20_000
auto_detect_solc = true
evm_version = "cancun"
extra_output = ["storageLayout"]

[profile.ci]
verbosity = 4

[rpc_endpoints]
amoy = "${AMOY_ENDPOINT}${ALCHEMY_API_KEY}"
