
# When running forge, you can specify the profile to use using the FOUNDRY_PROFILE environment variable.
[profile.default]
solc = '0.8.26'
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
via_ir = true
cache_path = 'cache'
gas_reports = ["*"]
# offline = false
ffi = true
ast = true
build_info = true
optimizer = true
optimizer_runs = 20_000
auto_detect_solc = false
evm_version = "paris"
extra_output = ["storageLayout"]

[profile.ci]
verbosity = 4

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"

[etherscan]
amoy = { key = "${AMOY_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }