name: CI

on:
  workflow_call:
  # https://github.com/marketplace/actions/jest-coverage-report#forks-with-no-write-permission
  pull_request:

jobs:
  ci:
    name: Static Analysis and Test | Node ${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js v${{matrix.node}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: npm ci

      - name: Run static analysis
        run: make lint

      - name: Run security tests
        run: make sectest

      - name: Test
        run: make test

