name: CI

on:
  workflow_call:
  # https://github.com/marketplace/actions/jest-coverage-report#forks-with-no-write-permission
  pull_request:

jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
      
      - name: Collecting .env from dotenv-vault
        run: npx dotenv-vault@latest pull -m ${{ secrets.DOTENV_ME }} -y
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run static analysis
        run: make lint

  test:
    name: Test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Collecting .env from dotenv-vault
        run: npx dotenv-vault@latest pull -m ${{ secrets.DOTENV_ME }} -y
      
      - name: Install dependencies
        run: npm ci
            
      - name: Test
        run: make test
    