---
name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: eslint linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install standard
      - run: make lint

  solhint:
    name: solhint linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install solhint
      - run: make solhint